---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/{id}":
    parameters:
    - name: accept
      in: headers
      description: accept header
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - email
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: api.lvh.me:8080
